### ISSUE TITLE
Card not loading in lovelace

### ISSUE THREAD

**Issue by ga2pegw** [ljmerza/our-groceries-card#9]
I installed the card through HACS, put the integration in my configuration.yaml and added the lines under resources in my Lovelace raw config, but when trying to add the card into my Lovelace view, I get "Custom element doesn't exist: our-groceries-card". 

Running Home Assistant Core 0.105.4
Host OS: Ubuntu 18.04 LTS
Hardware: Intel NUC

**Comment by ljmerza** [comment]
is the card js file being downloaded in the network tab?

**Comment by ga2pegw** [comment]
Not sure what you mean by network tab

**Comment by ljmerza** [comment]
developer network tab

**Comment by DennisOtt-git-hub** [comment]
I have just experience the same issue in trying to set up the OurGroceries card.  The sensor is showing up correctly.  I have installed through HACS and added all entries in the configuration yaml as shown in the repository instructions.  I get the 'Custom element doesn't exist: our-groceries-card.' message on the lovelace page.  I am on HA core-2021.2.3 running in Ubuntu 18.04.

**Comment by DennisOtt-git-hub** [comment]
Please disregard the previous problem message.  When I revisited this today (three days later) it seems to cleared up.  I am now seeing the lists and the card is found.

**Comment by Danie10** [comment]
Also get the 'Custom element doesn't exist: our-groceries-card.' message on the Lovelace page after configuration and rebooted HA. The entity is correctly there as I can the list names etc in the Developer pages.

Maybe the Redame.md file just needs to explain otherwise that the card needs a day or two to do something before we see it correctly? My expectation was once the login worked and pulled the list names through, it was ready for use in an entity card.
